#!/usr/bin/env python
import sys

# encode_pass <pass> <iv>

plain = sys.argv[1].strip()

iv = int(sys.argv[2])
encoded = []
for l in plain:
    iv = iv ^ ord(l)
    encoded.append(iv)

print("input    : %s" % plain)
print("plaintext: %s" % " ".join([str(ord(i)) for i in plain]))
print("encoded  : %s" % " ".join([str(i) for i in encoded]))

